### ISSUE TITLE
Installation instructions are missing one step

### ISSUE THREAD

**Issue by batjko** [MrWillCom/hexo-theme-cupertino#1]
Hi there,

I've just installed your theme as described in the README, i.e. I cloned the theme into the `themes` subfolder, and then changed the theme in the main `_config.yml`.

However, when I then start `hexo server`, I get this error.

![image](https://user-images.githubusercontent.com/7287076/102013528-ae87b100-3d48-11eb-8aab-6b266206dea9.png)

...and the webpage does not show up. 
It seems Hexo cannot find the theme if the project is merely cloned as-is.

One also needs to change the target folder when cloning, so 
`git clone https://github.com/MrWillCom/hexo-theme-cupertino.git` 
should be:
`git clone https://github.com/MrWillCom/hexo-theme-cupertino.git cupertino`

**Comment by MrWillCom** [comment]
Thanks. You are right. It's necessary to move `themes/hexo-theme-cupertino/` to `themes/cupertino/` .

**Comment by MrWillCom** [comment]
It's fixed now. :smiley: 53264e6

**Comment by batjko** [comment]
That's super-fast turnaround!
