### ISSUE TITLE
A suggestion for light/dark mode transitions

### ISSUE THREAD

**Issue by anywne** [MrWillCom/hexo-theme-cupertino#10]
Hi there,

Is it possible to add a transition animation to the light/dark mode switching of the post page? just like the home page. I mean the `About this Post` area at the bottom of the post page.I always feel that the change of the post page is a bit abrupt.

Thank you.

**Comment by MrWillCom** [comment]
e1a4e07 added this feature! 🎉

Thanks for your suggestion!

**Comment by anywne** [comment]
Wow, awesome. Thank you. 
But just now I found another bug about light/dark mode. A problem has arisen since the theme doesn't use js-cookie. For example, I switched to dark mode on the page of an article, but I found that it was still light when I returned to other pages.

**Comment by MrWillCom** [comment]
Cookie is a little bit confusing, but still, I've fixed it now. e7654a2
