### ISSUE TITLE
tags page & search

### ISSUE THREAD

**Issue by Poorandy** [MrWillCom/hexo-theme-cupertino#11]
Really like your design. several suggestions:

add a tag page to get posts by tags.
add ICP filing configuration.
add a search button for docsearch.

**Comment by MrWillCom** [comment]
Thank you for your suggestions! I'll consider adding these features in the future. 🚀

**Comment by MrWillCom** [comment]
> add a tag page to get posts by tags.

Now available, but a few more steps required, check out [docs](https://github.com/MrWillCom/hexo-theme-cupertino/blob/master/docs/features/tags-and-categories.md).

---

> add ICP filing configuration.

You can use this to show your ICP information:

https://github.com/MrWillCom/hexo-theme-cupertino/blob/fb92a7e512cb7844f61bc5d3928c742d4e822a1a/_config.yml#L97

---

> add a search button for docsearch.

Available, a few more steps required, check out [docs](https://github.com/MrWillCom/hexo-theme-cupertino/blob/master/docs/features/search.md).

Finally, thanks for your suggestions which means a big leap for Theme Cupertino!
