### ISSUE TITLE
TOC request

### ISSUE THREAD

**Issue by Loudomian** [MrWillCom/hexo-theme-cupertino#12]
I'm glad tag and categories were added to this theme, it enriches the reader's experience and completes the ongoing usability of this theme, while the rainbow banner looks great.

It would be great to see toc added in the future as well.

**Comment by MrWillCom** [comment]
Thanks! I may implement this feature in the future.

**Comment by MrWillCom** [comment]
Done! Check it out by updating the theme! 🎉
