### ISSUE TITLE
标题样式建议

### ISSUE THREAD

**Issue by anywne** [MrWillCom/hexo-theme-cupertino#13]
对于主题的样式，我想提一个建议：

我发现一级标题和二级标题字号是相同的，这样就很难分别一 二级标题，而三、四、五、六级标题几乎很少用到。

所以我的建议是，把所有标题的字号全部设置为相同，然后在不同级别标题的左侧加一个 `H1` `H2` 类似的小标识，用以分辨不同级别的标题。

也可以为标题设置一个不同于正文的颜色，这样便于分辨正文与标题。

灵感来源于 Effie：

![](https://static.effie.co/static/dist/img/Surface_w.f013c9a.png)

**Comment by MrWillCom** [comment]
感谢你的建议。

目前标题字号我都还没有更改，保持浏览器提供的默认大小，所以一级和二级标题的字号是一样的。我会在以后做调整。
