### ISSUE TITLE
Waline Config Error

### ISSUE THREAD

**Issue by lujiannan** [MrWillCom/hexo-theme-cupertino#16]
第一个BUG：这里的serverURL必须以 "'https://'''（双引号套单引号），以"https://"（双引号）或是以'https://‘（单引号）都会出错
![image](https://user-images.githubusercontent.com/56606587/178949017-cd601f06-e0da-4ff0-8826-69bee85f3575.png)
第二个BUG：配置waline时添加boolean类型的属性时正常，但是要添加如requiredMeta的属性时，评论区会消失
![image](https://user-images.githubusercontent.com/56606587/178949523-f5042f15-9b8c-482c-836c-b5a76f75e836.png)

**Comment by MrWillCom** [comment]
你好！Hexo 配置文件使用的是 YAML 语法，而不是 JavaScript 语法。在外层使用一对引号会让 YAML 认为它是字符串，和不加引号是一样的。加双层不同引号可以避免混淆，同时把引号也渲染到 HTML 文件里的 `<script />` 元素里。

所以这样是不行的：

**YAML**:

```yaml
url: "https://example.com/"
requiredMeta: "nick"
```

**JavaScript**:

```js
... {
  url: https://example.com/,
  //        ^ syntax error
  requiredMeta: nick,
  //            ^ `nick` is not defined
}
```

要改成这样：

**YAML**:

```yaml
url: "'https://example.com/'"
requiredMeta: "'nick'"
```

**JavaScript**:

```js
... {
  url: 'https://example.com/',
  requiredMeta: 'nick',
}
```

**Comment by jonie-ritie** [comment]
![image](https://user-images.githubusercontent.com/108459621/178957864-7bb06b04-0857-4acb-8d57-fd6bef28386b.png)

**Comment by MrWillCom** [comment]
文档要求似乎是字符串数组，好像不是字符串吧。

https://waline.js.org/reference/component.html#requiredmeta

**Comment by jonie-ritie** [comment]
我都试过了太难了

**Comment by MrWillCom** [comment]
好吧。可以检查一下控制台有没有错误吗？

**Comment by jonie-ritie** [comment]
![image](https://user-images.githubusercontent.com/108459621/178959232-23028af5-b667-4fbf-8eb1-101e0248b8d4.png)
这是我使用 ['nick']作为属性传入时的控制台报错

**Comment by MrWillCom** [comment]
试下这个？

```yaml
requiredMeta: "['nick']"
```

**Comment by jonie-ritie** [comment]
哥，你是我的神，谢谢哥

**Comment by jonie-ritie** [comment]
我觉得如果可以的话，在waline的doc下写一个例子，我觉得我这样的傻子不少

**Comment by jonie-ritie** [comment]
还有一个问题
![image](https://user-images.githubusercontent.com/108459621/178965695-a0be7441-2b78-43a6-9074-d2fe834e9fd5.png)
对于我们的主题，我应该怎么配置呢

**Comment by MrWillCom** [comment]
> 我觉得如果可以的话，在waline的doc下写一个例子，我觉得我这样的傻子不少

801bef8 更新了 docs

**Comment by MrWillCom** [comment]
> 还有一个问题
> ![image](https://user-images.githubusercontent.com/108459621/178965695-a0be7441-2b78-43a6-9074-d2fe834e9fd5.png)
> 对于我们的主题，我应该怎么配置呢

在 `<html />` 元素上有一个 `data-color-scheme` 属性，值为 `"auto"`、`"light"` 或 `"dark"`。`"auto"` 的时候是跟随浏览器设置，因此有两种情况，可以试试用 JS 获取这个属性值然后看情况用 media 查询来获取深色模式状态。
