### ISSUE TITLE
Code blocks are flowing to the left

### ISSUE THREAD

**Issue by batjko** [MrWillCom/hexo-theme-cupertino#2]
Hi again,

After installing the theme, I find that code blocks are now flowing all the way to the left, where they don't belong:
![image](https://user-images.githubusercontent.com/7287076/102014016-a67d4080-3d4b-11eb-90b8-c43ef1993844.png)

Any idea why that may be?

**Comment by MrWillCom** [comment]
Hello, I think it's okay in my browser. Could you please tell me more information about your browser? Thanks!

**Comment by batjko** [comment]
Latest Chrome, Windows 10 64bit

**Comment by MrWillCom** [comment]
I think it's okey here.

![A screenshot on my device](https://user-images.githubusercontent.com/47271684/103135560-113b5e00-46f4-11eb-9c8a-520d3273e56f.png)

**Comment by ddmtrius** [comment]
[Untitled-2.txt](https://github.com/MrWillCom/hexo-theme-cupertino/files/9250153/Untitled-2.txt)
Hi Mr. Will, I have copied the source code of a post page and saved them as a text file, I hope this will help you a little.

**Comment by MrWillCom** [comment]
I think I got it, #25 fixed this issue. Now the code blocks look normal. You can preview this by switching to pull request #25.
