### ISSUE TITLE
表格增加边框线

### ISSUE THREAD

**Issue by anywne** [MrWillCom/hexo-theme-cupertino#23]
表格没有边框线，有时甚至看不出来是表格。

另外，主题文章页可否直接使用[github-markdown](https://github.com/sindresorhus/github-markdown-css)的样式呢？

**Comment by MrWillCom** [comment]
> 表格没有边框线，有时甚至看不出来是表格。

Now WIP in [branch 23-table](https://github.com/MrWillCom/hexo-theme-cupertino/tree/23-table).

> 另外，主题文章页可否直接使用[github-markdown](https://github.com/sindresorhus/github-markdown-css)的样式呢？

主题的设计参照 Apple Newsroom，表格的设计没找到参照，所以一直没有写。但是 GitHub Markdown 的表格设计应该可以参照一下，其它就不大改了。

**Comment by anywne** [comment]
> > 表格没有边框线，有时甚至看不出来是表格。
> 
> Now WIP in [branch 23-table](https://github.com/MrWillCom/hexo-theme-cupertino/tree/23-table).
> 
> > 另外，主题文章页可否直接使用[github-markdown](https://github.com/sindresorhus/github-markdown-css)的样式呢？
> 
> 主题的设计参照 Apple Newsroom，表格的设计没找到参照，所以一直没有写。但是 GitHub Markdown 的表格设计应该可以参照一下，其它就不大改了。

原来是这样啊，那我觉得可以参考一下这个hugo主题：https://github.com/onweru/newsroom
