### ISSUE TITLE
请问friends和projects的选项卡如何配置？

### ISSUE THREAD

**Issue by glut410** [MrWillCom/hexo-theme-cupertino#26]

**Comment by MrWillCom** [comment]
你可以通过创建自定义的页面来实现 friends 和 projects 页。

```sh
# See: https://hexo.io/docs/writing.html
$ hexo new page <title>
```

可以参照我的：

- https://github.com/MrWillCom/MrWillCom.github.io/blob/master/source/friends/index.md
- https://github.com/MrWillCom/MrWillCom.github.io/blob/master/source/projects/index.md

**Comment by glut410** [comment]
感谢！
