### ISSUE TITLE
请问，主页里面mr.will is talking here 是在哪里配置的啊

### ISSUE THREAD

**Issue by Ilak-0** [MrWillCom/hexo-theme-cupertino#34]
我按照说明导入配置后，目前主页没有mr.will is talking here。导致进入界面会有一片空白。😂

**Comment by MrWillCom** [comment]
在 `_config.yml`（不是主题配置）里：

```yaml
description: Mr. Will is talking here.
```

也可参考 [MrWillCom/MrWillCom.github.io](https://github.com/MrWillCom/MrWillCom.github.io)

https://github.com/MrWillCom/MrWillCom.github.io/blob/55c7fca50c466bf0b8e7fd0738d4e27bd63fa887/_config.yml#L8

**Comment by Ilak-0** [comment]
谢谢
