### ISSUE TITLE
ios系统下tidio显示异常

### ISSUE THREAD

**Issue by MrWensen** [MrWillCom/hexo-theme-cupertino#35]
在iphone默认开启黑暗模式下safari浏览器打开网站后tidio会产生一个正方形的白框，我找了很久没找到去除的方法。另外电脑界面中如果将tidio靠边现实的话，在tidio里外观设置中调节，也会产生白色的长方形底图无法去除，求解决![image](https://user-images.githubusercontent.com/105364124/205450658-dae395c2-1dae-41bf-a847-cf858acff5f5.jpeg)

**Comment by MrWillCom** [comment]
Fixed in https://github.com/MrWillCom/hexo-theme-cupertino/commit/60ab2e41278ba5046f2cc30f975601832d187ac6
