### ISSUE TITLE
关于description换行问题

### ISSUE THREAD

**Issue by JinchuanL** [MrWillCom/hexo-theme-cupertino#37]
Hello～在hexo根目录里的_config.yml的description选项中，如果想要展示多行文字，应该怎么写呢？

_config.yml
> description: Hello, Andy

想要的效果是：
Hello,
Andy
而不是Hello, Andy

网上查了一圈能试的都试了，使用\n, |-, \<br>都不行....

**Comment by MrWillCom** [comment]
64184b0 不再转译 description。

更新主题后，你就可以使用 `<br>` 来换行了。

**Comment by JinchuanL** [comment]
谢谢辛苦啦～
