### ISSUE TITLE
Question about the comment system

### ISSUE THREAD

**Issue by MRX-J0BS** [MrWillCom/hexo-theme-cupertino#39]
Can this theme be adapted to comment systems such as valine?

**Comment by MrWillCom** [comment]
Valine isn't supported currently, maybe you should consider [Waline](https://waline.js.org/) and [giscus](https://giscus.app/). If you have to use Valine, please just tell me and I may integrate it later.

**Comment by MrWillCom** [comment]
It seems like [Valine](https://github.com/xCss/Valine) is no longer updating, you should migrate to [Waline](https://waline.js.org/) or some other comment services. If you need instructions, check out [Waline integration](https://cupertino.mrwillcom.com/integrations/waline) or [giscus integration](https://cupertino.mrwillcom.com/integrations/giscus).
