### ISSUE TITLE
[Feature Request] Increase readability of the Article page

### ISSUE THREAD

**Issue by aeilot** [MrWillCom/hexo-theme-cupertino#4]
## Screenshot
<img width="781" alt="截屏2021-07-03 下午12 23 28" src="https://user-images.githubusercontent.com/25583228/124342825-79b24d00-dbf9-11eb-8695-5ef752fd5339.png">

<img width="781" alt="截屏2021-07-03 下午12 25 54" src="https://user-images.githubusercontent.com/25583228/124342874-d150b880-dbf9-11eb-85a0-445334c348f1.png">

**The former: hexo-theme-cupertino**.  **The later: Apple Newsroom**.

## Describe the proposal
It seems that the line spacing and the font size is too small and not suitable for reading. And I suggests increasing readability of the Article page. All the adjustments can be done simply by modifying the CSS files.

Hope you'll adopt my proposal. Thanks! :)

**Comment by aeilot** [comment]
In addition, I love the Apple Newsroom's page margin. I hope you will imitate it.

**Comment by MrWillCom** [comment]
49581a8 updated the line height.

**Comment by aeilot** [comment]
There's another feature request that I'd love to add here. 

![IMAGE 2021-07-08 22:01:59](https://user-images.githubusercontent.com/25583228/124935301-1e88bc00-e038-11eb-8367-a04f7dd5391d.jpg)

Could you please modify the color of these links. I think gray might be a best choice.

**Comment by MrWillCom** [comment]
> There's another feature request that I'd love to add here.
> 
> ![IMAGE 2021-07-08 22:01:59](https://user-images.githubusercontent.com/25583228/124935301-1e88bc00-e038-11eb-8367-a04f7dd5391d.jpg)
> 
> Could you please modify the color of these links. I think gray might be a best choice.

019312e changed this.

**Comment by aeilot** [comment]
Thanks for these modifications but I wonder if you can make the animation of these links the same as the links in the top bar.

**Comment by MrWillCom** [comment]
> Thanks for these modifications but I wonder if you can make the animation of these links the same as the links in the top bar.

Maybe not. Apple's site doesn't have any transition for the footer links, and it is not neccesary, so I won't add animation to these links. Sorry.
