### ISSUE TITLE
鼠标悬停放大图片的效果如何关闭

### ISSUE THREAD

**Issue by uniech** [MrWillCom/hexo-theme-cupertino#40]
我找不到应该修改那个文件

**Comment by MrWillCom** [comment]
你好，主题其实不包含鼠标悬停放大的效果，你可以试着检查一下是不是某个浏览器插件提供了这个功能

**Comment by MrWillCom** [comment]
哦哦不好意思，如果你是指文章列表里的封面悬停放大的话，你可以把这行删掉：

https://github.com/MrWillCom/hexo-theme-cupertino/blob/64184b0e74a47e55f09961fdb86c13ccaaf43ac8/source/css/post-list.css#L55
