### ISSUE TITLE
Page theme control button not aligned

### ISSUE THREAD

**Issue by CLCK0622** [MrWillCom/hexo-theme-cupertino#41]
As mentioned above, the button is not vertically aligned. 
![image](https://github.com/MrWillCom/hexo-theme-cupertino/assets/36215258/3bc47ee1-ca4d-4ed1-80fe-d45af0c14f85)
Moreover, I suppose using a flex display and putting this button on the right-bottom corner will be better. 
Looking forward to your reply!

**Comment by MrWillCom** [comment]
Now it looks like this 👀:

![screenshot of the recently fixed switch](https://github.com/MrWillCom/hexo-theme-cupertino/assets/47271684/71210609-b37a-4c3f-b1b3-90a47d036e4e)
