### ISSUE TITLE
search function

### ISSUE THREAD

**Issue by aliangdev** [MrWillCom/hexo-theme-cupertino#46]

**Comment by aliangdev** [comment]
At the beginning, I modified the theme **_ config.yml** according to the operating instructions, but the search function did not return any results. According to the plugin prompts, in the root directory **_ config.yml** runs normally after adding the following code:

Search:
    Path: search.json
    Field: post
    Content: true
    Template:/ Search.xml

**Comment by JinchuanL** [comment]
https://cupertino.mrwillcom.com/extra-features/search 

Try this.
