### ISSUE TITLE
Incorrect Quote Padding

### ISSUE THREAD

**Issue by JinchuanL** [MrWillCom/hexo-theme-cupertino#47]
<img width="745" alt="截屏2024-01-06 下午7 14 49" src="https://github.com/MrWillCom/hexo-theme-cupertino/assets/68026794/d091fa44-a4de-447c-96e5-2f94b2a4104d">

If I am using the list in quotes, the padding is incorrect.

**Comment by MrWillCom** [comment]
Thanks for the feedback. Could you please show some demo Markdown code to reproduce this?

**Comment by JinchuanL** [comment]
Sure, try this:

1. List item1.

   > This is a quote
   >
   > 1. List item 1 in quote
   > 2. List item 2 in quote
   > 3. List item 3 in quote

**Comment by JinchuanL** [comment]
> Thanks for the feedback. Could you please show some demo Markdown code to reproduce this?

Sure, try this:

![屏幕截图 2024-01-06 110804](https://github.com/MrWillCom/hexo-theme-cupertino/assets/68026794/7f9b0a24-0074-4bb4-a26e-13307e4c06f4)
