### ISSUE TITLE
配置无法覆盖

### ISSUE THREAD

**Issue by 0x587** [MrWillCom/hexo-theme-cupertino#51]
_config.cupertino.yml的列表无法覆盖默认配置

**Comment by MrWillCom** [comment]
Fixed in #52 ，感谢你的反馈！🙏

**Comment by MrWillCom** [comment]
由于配置文件的结构有些还没更新，在 `master` 分支上，这个问题可能没有解决。你可以暂时迁移至 `next` 分支，然后根据新的配置文件结构再做修改，nav 上的配置就可以正常覆盖了。footer 的话暂时还没修，但是会尽快的。

**Comment by MrWillCom** [comment]
https://github.com/MrWillCom/hexo-theme-cupertino/commit/c96d7fa1d48a6c48cbd48941849781c05575d434 修复了 footer 上的这个问题。
