### ISSUE TITLE
作者有没有把主题迁移hugo或Astro的打算🥺

### ISSUE THREAD

**Issue by xiaohui8** [MrWillCom/hexo-theme-cupertino#54]

**Comment by MrWillCom** [comment]
👋你好，非常感谢你提出的想法！不过，目前来说我是没有这样的打算的，把主题迁移到 Hugo 或者 Astro 对我来说恐怕不是很轻松。

你所提及的两种框架中，Hugo 的模版语法是 [Go 语言](https://pkg.go.dev/html/template) 提供的，Astro 的模版语法也是他们自己开发的，都不是静态网页生成器常用的模版语言 [EJS](https://ejs.co/) 或是 [Nunjucks](https://mozilla.github.io/nunjucks/)。这意味着把主题迁移到这两种框架将需要很大程度上的重写，工作量会非常大。

另外，使用这两种框架完成重写会使本项目的通用性降低，毕竟他们的模版语法只有他们自己能够处理。而本项目正使用的 EJS 或是别的一些成熟的模版语言往往受到更多生成器的支持，比如 [11ty](https://www.11ty.dev/)（另外提一嘴，[11ty 支持很多很多种模版语言](https://www.11ty.dev/docs/languages/)）。

对于我个人而言，空余时间也谈不上多，只有像寒暑假之类的时候才能有点时间系统性地更新自己的这些项目，所以更加没有迁移本项目的打算。

不过最近我正在更新本项目的 v2 版本，如果想要使用的话，可以选择 [`next`](https://github.com/MrWillCom/hexo-theme-cupertino/tree/next) 分支或者使用[发布在 npm 上的 beta 版本](https://www.npmjs.com/package/hexo-theme-cupertino)。

实际上，如果是我的话，我会觉得与其迁移主题，不如迁移自己现有的博客。毕竟迁移 Markdown 文件、改改配置之类的，比起重写主题真的要方便得多。

最后还是要感谢你提出这一想法🤝。Hugo 和 Astro 的确是十分先进的框架，要是有时间，我也许会用他们来试试完成一些小项目。
