### ISSUE TITLE
Enhancing Performance: Adjust Default Animation Settings for Better Compatibility

### ISSUE THREAD

**Issue by aeilot** [MrWillCom/hexo-theme-cupertino#61]
Hello,

I recently tried out the latest version of your theme and was impressed by the updates, especially the animations and fresh designs. However, I noticed that the default configuration, which includes blurring animations, may not be optimized for lower-performance devices. This can cause significant lag, particularly on mobile devices like mine.

To ensure smooth performance across all major devices, I suggest reconsidering the default animation settings to be more inclusive of various hardware capabilities.

These changes could make a great theme even better. I hope this feedback is helpful.

**Comment by MrWillCom** [comment]
That's true, the performance looks really bad on some devices because of the costly blur filter. I'll change the default configuration from enabled to disabled.

**Comment by MrWillCom** [comment]
271a6351caccbea1566bbcbd8d5efee0d6cad7fd has made this change, which will be available in the next pre-release.
