### ISSUE TITLE
Navigation icons won't change in light mode

### ISSUE THREAD

**Issue by ZhuoYun233** [MrWillCom/hexo-theme-cupertino#8]
![cantChange](https://user-images.githubusercontent.com/82555949/167622272-1a282c14-30b2-4869-bc11-0922ec5de43f.png)
Thanks for the great theme! But here is an issue. When changed to light mode, icons tope right remained to be white. Maybe they are supposed to change with color scheme?

**Comment by MrWillCom** [comment]
Thanks for your feedback. This bug is now fixed in commit dbda0c8 🎉 .
